import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_DocumentationFunctionality_UploadDocument

CucumberKW.runWithCucumberRunner(Runner_DocumentationFunctionality_UploadDocument.class)

