import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import soapnotes.CR_CreateScheduleAppointment

CucumberKW.runWithCucumberRunner(CR_CreateScheduleAppointment.class)
