import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import carecoordination_leftfilters.CR_ServingFacilityFilters

CucumberKW.runWithCucumberRunner(CR_ServingFacilityFilters.class)
