import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_ClinicalSection_DeleteProcedureResult

CucumberKW.runWithCucumberRunner(Runner_ClinicalSection_DeleteProcedureResult.class)

