import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_DocumentationFunctionality_DeleteDocument

CucumberKW.runWithCucumberRunner(Runner_DocumentationFunctionality_DeleteDocument.class)

