<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>obj_verifyenrolmentcc</name>
   <tag></tag>
   <elementGuidId>ba887aed-d855-422e-a2c1-5afd27c662c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>div#tocGrid>div.k-grid-content.k-auto-scrollable>table>tbody>tr>td:nth-child(8)</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div#tocGrid>div.k-grid-content.k-auto-scrollable>table>tbody>tr>td:nth-child(8)</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ProgramEnrollment/frameObject</value>
   </webElementProperties>
</WebElementEntity>
