import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW
import patientGrid.Runner_CareGaps

import runnerPackage.Runner_CreateTaskYearlyReccurence

CucumberKW.runWithCucumberRunner(Runner_CreateTaskYearlyReccurence.class)

