import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_LeftFilter_UM_AttributedFacility

CucumberKW.runWithCucumberRunner(Runner_LeftFilter_UM_AttributedFacility.class)

