import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_HighAlertCaregap_AddHighAlert

CucumberKW.runWithCucumberRunner(Runner_HighAlertCaregap_AddHighAlert.class)

