import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_DemoGraphics_CreateNewPatient

CucumberKW.runWithCucumberRunner(Runner_DemoGraphics_CreateNewPatient.class)

