import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_ProgramEnrollment_SetProgramEnrollmentSearchpatient

CucumberKW.runWithCucumberRunner(Runner_ProgramEnrollment_SetProgramEnrollmentSearchpatient.class)

