import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_ProgramEnrollment_EditProgramEnrollmentCCGridOpenedPatient

CucumberKW.runWithCucumberRunner(Runner_ProgramEnrollment_EditProgramEnrollmentCCGridOpenedPatient.class)

