import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_Contacts_DeleteSupportPerson

CucumberKW.runWithCucumberRunner(Runner_Contacts_DeleteSupportPerson.class)

