import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_LeftFilter_P_Program_Enrollment

CucumberKW.runWithCucumberRunner(Runner_LeftFilter_P_Program_Enrollment.class)

