import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW
import patientGrid.Runner_CareGaps

import runnerPackage.Runner_CreateTaskDailyReccurence

CucumberKW.runWithCucumberRunner(Runner_CreateTaskDailyReccurence.class)

