import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_DischargeFunctionality_DischargewithDischargeDate

CucumberKW.runWithCucumberRunner(Runner_DischargeFunctionality_DischargewithDischargeDate.class)

