import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_ClinicalSection_EditImagingResult

CucumberKW.runWithCucumberRunner(Runner_ClinicalSection_EditImagingResult.class)

