import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW
import clinicalPackage.Runner_ClinicalSectionEdited

CucumberKW.runWithCucumberRunner(Runner_ClinicalSectionEdited.class)
