import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_ClinicalSection_AddImagingResult

CucumberKW.runWithCucumberRunner(Runner_ClinicalSection_AddImagingResult.class)

