import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_DemoGraphics_SetPatientPreference

CucumberKW.runWithCucumberRunner(Runner_DemoGraphics_SetPatientPreference.class)

