import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_ClinicalSection_DeleteImmunization

CucumberKW.runWithCucumberRunner(Runner_ClinicalSection_DeleteImmunization.class)

