import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import frompreviouscareplan.CR_FromPreviousCarePlan_BOPMR

CucumberKW.runWithCucumberRunner(CR_FromPreviousCarePlan_BOPMR.class)
