import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_LeftFilter_UMP_MultiFacility

CucumberKW.runWithCucumberRunner(Runner_LeftFilter_UMP_MultiFacility.class)

