import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import based_on_patient_medical_record.CR_WIPBySaveCloseBtn

CucumberKW.runWithCucumberRunner(CR_WIPBySaveCloseBtn.class)
