import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import carecoordination_leftfilters.CR_EncounterTypeFilters

CucumberKW.runWithCucumberRunner(CR_EncounterTypeFilters.class)
