import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_LeftFilter_LeftFiltersPatientGrid

CucumberKW.runWithCucumberRunner(Runner_LeftFilter_LeftFiltersPatientGrid.class)

