import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import runnerPackage.Runner_CareTeam_CareManager_DeleteCareManager

CucumberKW.runWithCucumberRunner(Runner_CareTeam_CareManager_DeleteCareManager.class)

