import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import patientGrid.Runner_CareCoordinationLeftFilters

CucumberKW.runWithCucumberRunner(Runner_CareCoordinationLeftFilters.class)
