import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import careplan_blank.CR_PrintByWIPStatus_PatientCarePlan

CucumberKW.runWithCucumberRunner(CR_PrintByWIPStatus_PatientCarePlan.class)
