import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_CareTeam_CarePhysician_AddCarePhysicianSDatelesstoCDateEDateGreaterToCDate

CucumberKW.runWithCucumberRunner(Runner_CareTeam_CarePhysician_AddCarePhysicianSDatelesstoCDateEDateGreaterToCDate.class)

