<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Obj_SeverityType</name>
   <tag></tag>
   <elementGuidId>70b2def6-fe57-4be3-9edf-b52a7c51d533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#appCCM</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;appCCM&quot;)[count(. | //iframe[@name = 'appCCM' and @id = 'appCCM' and @data-loaded = 'false' and @data-src = '/CareManagement?fromPersiviaPortal=true&amp;userName=zl@slt.com&amp;sessionId=7CF803CB-4A8A-427F-ACA2-75B4294DB2FD&amp;parentUserName=&amp;parentUserId=-1&amp;view=careCoordination' and @height = '700' and @width = '100%' and @src = '/CareManagement?fromPersiviaPortal=true&amp;userName=zl@slt.com&amp;sessionId=7CF803CB-4A8A-427F-ACA2-75B4294DB2FD&amp;parentUserName=&amp;parentUserId=-1&amp;view=careCoordination']) = count(//iframe[@name = 'appCCM' and @id = 'appCCM' and @data-loaded = 'false' and @data-src = '/CareManagement?fromPersiviaPortal=true&amp;userName=zl@slt.com&amp;sessionId=7CF803CB-4A8A-427F-ACA2-75B4294DB2FD&amp;parentUserName=&amp;parentUserId=-1&amp;view=careCoordination' and @height = '700' and @width = '100%' and @src = '/CareManagement?fromPersiviaPortal=true&amp;userName=zl@slt.com&amp;sessionId=7CF803CB-4A8A-427F-ACA2-75B4294DB2FD&amp;parentUserName=&amp;parentUserId=-1&amp;view=careCoordination'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td [@data-container-for='severityType'] //span [@class='k-dropdown-wrap k-state-default']//span[@class='k-select'] </value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appCCM</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appCCM</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>/CareManagement?fromPersiviaPortal=true&amp;userName=zl@slt.com&amp;sessionId=7CF803CB-4A8A-427F-ACA2-75B4294DB2FD&amp;parentUserName=&amp;parentUserId=-1&amp;view=careCoordination</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>700</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/CareManagement?fromPersiviaPortal=true&amp;userName=zl@slt.com&amp;sessionId=7CF803CB-4A8A-427F-ACA2-75B4294DB2FD&amp;parentUserName=&amp;parentUserId=-1&amp;view=careCoordination</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appCCM&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR_PatientGrid/OR_PatientData/OR_Clinical Section/OR_ProblemList/Obj_frame</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td [@data-container-for='severityType'] //span [@class='k-dropdown-wrap k-state-default']//span[@class='k-select'] </value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td [@data-container-for='severityType'] //span [@class='k-dropdown-wrap k-state-default']//span[text()='Select']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td [@data-container-for='severityType'] //span [@class='k-dropdown-wrap k-state-default']//span[text()='Select']</value>
   </webElementXpaths>
</WebElementEntity>
