import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_DemoGraphics_DeletePatientPic

CucumberKW.runWithCucumberRunner(Runner_DemoGraphics_DeletePatientPic.class)

