import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW
import patientGrid.Runner_CareGaps

import runnerPackage.Runner_CreateTasknoReccurence

CucumberKW.runWithCucumberRunner(Runner_CreateTasknoReccurence.class)

