import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import based_on_patient_medical_record.CR_Components_HideShow

CucumberKW.runWithCucumberRunner(CR_Components_HideShow.class)
