import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW
import patientGrid.Runner_CareGaps

import runnerPackage.Runner_CreateTaskMonthlyReccurence

CucumberKW.runWithCucumberRunner(Runner_CreateTaskMonthlyReccurence.class)

