import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import based_on_patient_medical_record.CR_PrintByDraftStatus_PatientCarePlan

CucumberKW.runWithCucumberRunner(CR_PrintByDraftStatus_PatientCarePlan.class)
