import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW

import carecoordination_leftfilters.CR_NotificationTypeFilters

CucumberKW.runWithCucumberRunner(CR_NotificationTypeFilters.class)
